#!/bin/sh

# test
npm run test --if-present

# format the code and commit it
npm run format --if-present

# commit the code when it's formatted
git add .
git diff --quiet && git diff --staged --quiet || git commit -m "format"
